services:

  mattermost:
    container_name: mattermost
    image: mattermost/mattermost-team-edition
    ports:
      - "8065:8065"
    environment:
      - MM_USERNAME=${MATTERMOST_DB_USER}
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_SQLSETTINGS_DATASOURCE=${MATTERMOST_DB_USER}:${MATTERMOST_DB_PASSWORD}@tcp(mysql-mattermost:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
      - MM_PASSWORD=${MATTERMOST_DB_PASSWORD}
      - MM_DBNAME=${MATTERMOST_DB}
      - DB_PORT_PORT_NUMBER=3306
      - DB_HOST=mysql-mattermost
    depends_on:
      - mysql-mattermost
    volumes:
      - mattermost_data:/mattermost/data:rw
      - mattermost_config:/mattermost/config:rw
      - mattermost_plugins:/mattermost/plugins:rw
      - mattermost_logs:/mattermost/logs:rw

  mysql-mattermost:
    image: mysql:latest
    container_name: mysql-mattermost
    environment:
    - TZ=Europe/Rome
    - MYSQL_USER=${MATTERMOST_DB_USER}
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_PASSWORD=${MATTERMOST_DB_PASSWORD}
    - MYSQL_DATABASE=${MATTERMOST_DB}
    volumes:
      - mysql-mattermost:/var/lib/mysql

volumes:
  mattermost_data:
  mattermost_config:
  mattermost_logs:
  mattermost_plugins:
  mysql-mattermost:

